Projekt/Models/Classes/MovieDetails.cs
using Projekt.Data;
using System.ComponentModel.DataAnnotations;

namespace Projekt.Models
{
    public class MovieDetails
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ImageURL { get; set; }
        public MovieCategory MovieCategory { get; set; }
        public int ReleaseYear { get; set; }
    }
}

Projekt/Controllers/MovieDetailsController.cs
using Microsoft.AspNetCore.Mvc;
using Projekt.Data;
using Projekt.Models;
using Projekt.Models.Classes;
using Projekt.Models.DTO;

namespace Projekt.Controllers
{
    public class MovieDetailsController : Controller
    {
        private readonly AppDbContext _context;
        public MovieDetailsController (AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(int movieId)
        {
            MovieDetails movie = _context.MovieDetails.FirstOrDefault(m => m.Id == movieId);
            List<ScreenTime> screenTimes = new List<ScreenTime>();
            screenTimes = _context.ScreenTimes.Where(st => st.MovieId == movieId).ToList();
            MovieDetailsDto movieDetailsDto = new MovieDetailsDto()
            {
                Movie = movie,
                ScreenTime = screenTimes
            };

            return View(movieDetailsDto);
        }
        
        public IActionResult ScreenTime(int movieId)
        {
            MovieDetails movie = _context.MovieDetails.FirstOrDefault(m => m.Id == movieId);
            AddScreenTimeDto addScreenTimeDto = new AddScreenTimeDto()
            {
                MovieId = movieId,
                MovieTitle = movie.Title,
                ScreenTime = new ScreenTime()
            };

            return View("AddScreenTime", addScreenTimeDto);
        }

        [HttpPost]
        public IActionResult AddScreenTime(AddScreenTimeDto addScreenTimeDto)
        {

            var screenTime = new ScreenTime
            {
                MovieId = addScreenTimeDto.MovieId,
                ScreenDateTime = addScreenTimeDto.ScreenTime.ScreenDateTime
            };
            _context.Add(screenTime);
            _context.SaveChanges();
            ViewBag.Message = "Screening time was successfully added.";
            return View("AddScreenTime", addScreenTimeDto);
        }
        [HttpPost]
        public IActionResult DeleteScreenTime(int screenTimeId)
        {
            var screenTime = _context.ScreenTimes.FirstOrDefault(s => s.Id == screenTimeId);
            if (screenTime != null)
            {
                _context.ScreenTimes.Remove(screenTime);
                _context.SaveChanges();
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

Projekt/Views/MovieDetails/AddScreenTime.cshtml
@using Projekt.Models.DTO
@model AddScreenTimeDto

<div class="addScreenTimeContainer">
    <div>
        <h1>Add a new screentime</h1>
    </div>
    <div>
        @if (ViewBag.Message != null)
        {
            <div class="alert alert-success">@ViewBag.Message</div>
        }
        @using (Html.BeginForm("AddScreenTime", "MovieDetails", FormMethod.Post))
        {
            @Html.HiddenFor(model => model.MovieId)
            <div class="form-group">
                @Html.LabelFor(model => model.ScreenTime.ScreenDateTime, new { @class = "control-label" })
                @Html.TextBoxFor(model => model.ScreenTime.ScreenDateTime, "{0:yyyy-MM-dd hh:mm tt}", new { @class = "form-control datepicker", @placeholder = "YYYY-MM-DD HH:MM" })
                @Html.ValidationMessageFor(model => model.ScreenTime.ScreenDateTime, "", new { @class = "text-danger" })
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>

        }
    </div>
</div>

<style>

    .addScreenTimeContainer {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        flex-direction: column;
    }

    form {
        width: 100%;
        max-width: 600px;
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .form-group {
        width: 100%;
    }

    label {
        display: block;
        margin-bottom: 5px;
    }

    input[type="submit"] {
        margin-top: 20px;
    }
</style>

Projekt/Views/MovieDetails/Index.cshtml
@using Projekt.Models.Classes
@using Projekt.Models.DTO
@model MovieDetailsDto
@{
    Layout = "_Layout";
    bool isAdmin = User.IsInRole("Admin");
}
<body>
    <div class="container">
        <div class="admin-button @if(!isAdmin) {
        <text>hidden</text>}">
            @Html.ActionLink("Add Screening", "ScreenTime", "MovieDetails", new {movieId = @Model.Movie.Id})
        </div>

        <div class="right">
            <div class="movie-details-container">
                <h1>@Model.Movie.Title</h1>
                <div class="movie-poster">
                    <h7></h7>
                </div>
                <div class="movie-description">
                    <p>@Model.Movie.Description</p>
                </div>
                <div>
                    <div class="movie-screen-time-container">
                        @foreach (ScreenTime screenTime in Model.ScreenTime)
                        {
                            @Html.ActionLink(@screenTime.ScreenDateTime.ToString(), "SelectTickets", "Tickets", new {screenTimeId = @screenTime.Id, movieId = @Model.Movie.Id}, new { @class = "time-button" })
                        
                            @if (isAdmin)
                            {
                            <form method="post" action="@Url.Action("DeleteScreenTime", "MovieDetails", new { screenTimeId = @screenTime.Id })">
                                <input type="submit" value="Delete" />
                            </form>
                            }
                        }
                    </div>

                </div>
            </div>
        </div>

    </div>
    </div>
</body>
<style>
    body {
        background-color: #242333;
    }

    .container {
        display: flex;
    }

    .left {
        flex: 0 0 200px;
        background-color: black;
    }

    .right {
        flex: 1;
        padding: 20px;
    }

    .flow {
        display: flex;
        align-items: center;
        margin-bottom: 20px;
    }

        .flow h2 {
            margin-left: 10px;
            color: white;
        }

    .material-icons {
        font-size: 30px;
        color: white;
        margin-right: 10px;
    }

    .time-button {
        display: block;
        width: 80px;
        height: 40px;
        margin: 10px 0;
        text-align: center;
        background-color: #FFA500;
        color: black;
        font-size: 14px;
        border: none;
        border-radius: 5px;
        text-decoration: none;
    }

    .movie-description {
        color: rgb(200,200,200);
    }

    .admin-button {
        position: fixed;
        top: 20px;
        right: 20px;
        z-index: 999;
    }

        .admin-button.hidden {
            display: none;
        }

    .screen-time-button-container {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    .delete-button {
        margin-left: 10px;
    }

</style>